/* Product Data – shared between index and detail pages */
const products = [
  {
    id: 1,
    title: "Zahradní Harmonie",
    category: "mozaika",
    tag: "Mozaika",
    shortDesc: "Mozaikový obraz inspirovaný kouzlem zahrady",
    description: "Rozměrný mozaikový obraz zachycující krásu přírodní zahrady v plném květu. Složen z ručně řezaných dílků skla a keramiky v tónech zelené, zlaté a modré. Ideální jako dominanta obývacího pokoje nebo haly.",
    dimensions: "80 × 60 cm",
    material: "Sklo, keramika",
    technique: "Přímá metoda",
    colors: ["#2d5016", "#c9a84c", "#1e3a5f", "#8b4513"],
    price: "18 000 Kč",
    gradient: "linear-gradient(135deg, #1a3a0a 0%, #2d5016 30%, #c9a84c 60%, #1e3a5f 100%)"
  },
  {
    id: 2,
    title: "Azurový Sen",
    category: "fusing",
    tag: "Fusing",
    shortDesc: "Abstraktní fusing v odstínech moře",
    description: "Abstraktní kompozice evokující vlny a hloubku moře. Dílky z italského skleněného materiálu vytvářejí nádhernou hru světla a stínu. Dílo vyzařuje klid a harmonii.",
    dimensions: "60 × 60 cm",
    material: "Smalti, mramor",
    technique: "Fusing",
    colors: ["#0a4f7f", "#1e90ff", "#00bcd4", "#e0f7fa"],
    price: "12 000 Kč",
    gradient: "linear-gradient(135deg, #0a2a4f 0%, #0a4f7f 30%, #1e90ff 60%, #00bcd4 100%)"
  },
  {
    id: 3,
    title: "Slunečnicové Pole",
    category: "mikromozaika",
    tag: "Mikromozaika",
    shortDesc: "Zářivá mikromozaika plná letní energie",
    description: "Mikromozaika inspirovaná zlatými slunečnicovými poli jižní Moravy. Teplé tóny žluté, oranžové a hnědé vytvářejí energickou a radostnou kompozici. Každý dílek odráží sluneční paprsky jinak, dílo tak žije vlastním životem.",
    dimensions: "70 × 50 cm",
    material: "Sklo, zlacené tesery",
    technique: "Microtesera",
    colors: ["#f4a100", "#e65100", "#8d6e63", "#fff176"],
    price: "15 000 Kč",
    gradient: "linear-gradient(135deg, #5d3a00 0%, #e65100 30%, #f4a100 60%, #fff176 100%)"
  },
  {
    id: 4,
    title: "Geometrická Meditace",
    category: "mozaika",
    tag: "Mozaika",
    shortDesc: "Moderní geometrický vzor pro interiér",
    description: "Dekorativní mozaikový panel s precizním geometrickým vzorem. Čisté linie a kontrastní barvy vytvářejí moderní dílo vhodné do minimalistických interiérů. Pode na zavěšení nebo jako součást nábytku.",
    dimensions: "40 × 40 cm",
    material: "Keramika, přírodní kámen",
    technique: "Přímá metoda",
    colors: ["#1a1a2e", "#c9a84c", "#f5f0eb", "#4a4a6a"],
    price: "8 000 Kč",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #2a2a4a 25%, #c9a84c 50%, #f5f0eb 75%, #1a1a2e 100%)"
  },
  {
    id: 5,
    title: "Ptačí Oáza",
    category: "mikromozaika",
    tag: "Mikromozaika",
    shortDesc: "Barevná mikromozaika s ptáky",
    description: "Živý a barevný obraz zobrazující exotické ptáky mezi květy. Pestrá paleta barev osloví milovníky přírody a umění. Dílky jsou ručně tvarovány tak, aby dodaly peří plastický efekt.",
    dimensions: "90 × 60 cm",
    material: "Smalti, sklo, zlato",
    technique: "Microtesera",
    colors: ["#e53935", "#43a047", "#1e88e5", "#fdd835"],
    price: "25 000 Kč",
    gradient: "linear-gradient(135deg, #1a3322 0%, #43a047 25%, #e53935 50%, #1e88e5 75%, #fdd835 100%)"
  },
  {
    id: 6,
    title: "Stolní Deska – Riviera",
    category: "fusing",
    tag: "Fusing",
    shortDesc: "Fusingová stolní deska ve stylu Středomoří",
    description: "Zakázková fusingová stolní deska inspirovaná barvami italské riviéry. Odolný materiál vhodný i do exteriéru. Sklo je zpracováno tavením pro dlouhou životnost.",
    dimensions: "Ø 80 cm",
    material: "Mramor, travertin, keramika",
    technique: "Fusing",
    colors: ["#d4a373", "#264653", "#2a9d8f", "#e9c46a"],
    price: "32 000 Kč",
    gradient: "linear-gradient(135deg, #264653 0%, #2a9d8f 30%, #e9c46a 60%, #d4a373 100%)"
  },
  {
    id: 7,
    title: "Noční Květ",
    category: "vitraz",
    tag: "Vitráž",
    shortDesc: "Dekorativní vitráž s květinovým motivem",
    description: "Elegantní vitráž s motivem rozkvetlého květu v nočním měsíčním světle. Barevná skla střídavě odrážejí a propouštějí světlo a vytvářejí fascinující iluzi hloubky.",
    dimensions: "50 × 50 cm",
    material: "Sklo, perleť",
    technique: "Tiffany technika",
    colors: ["#1a0033", "#6a1b9a", "#ce93d8", "#ffc107"],
    price: "9 500 Kč",
    gradient: "linear-gradient(135deg, #1a0033 0%, #4a148c 30%, #6a1b9a 50%, #ce93d8 80%, #ffc107 100%)"
  },
  {
    id: 8,
    title: "Okno s Krajinou",
    category: "vitraz",
    tag: "Vitráž",
    shortDesc: "Vitráž pro vstupní prostor s motivem krajiny",
    description: "Rozsáhlá vitrážová kompozice realizovaná pro vstupní prostor soukromé vily. Motivy středomořské krajiny v barevných sklech. Vitráž je navržena tak, aby propouštěla světlo a zůstala krásná po desetiletí.",
    dimensions: "200 × 120 cm",
    material: "Barevné sklo, olovo",
    technique: "Klasická olověná vitráž",
    colors: ["#f5deb3", "#87ceeb", "#228b22", "#daa520"],
    price: "150 000 Kč",
    gradient: "linear-gradient(135deg, #1a3a0a 0%, #228b22 25%, #87ceeb 50%, #f5deb3 75%, #daa520 100%)"
  },
  {
    id: 9,
    title: "Abstrakce v Zlaté",
    category: "mikromozaika",
    tag: "Mikromozaika",
    shortDesc: "Luxusní abstraktní mikromozaika se zlatými akcenty",
    description: "Elegantní abstraktní mikromozaika kombinující matně černé dílky se zlatými a měděnými akcenty. Dílo vyzařuje luxus a rafinovanost. Ideální pro reprezentativní prostory, lobby hotelů nebo rezidence.",
    dimensions: "100 × 70 cm",
    material: "Sklo, 24k zlaté tesery, onyx",
    technique: "Microtesera",
    colors: ["#0d0d0d", "#c9a84c", "#b87333", "#2c2c2c"],
    price: "45 000 Kč",
    gradient: "linear-gradient(135deg, #0d0d0d 0%, #1a1a1a 30%, #c9a84c 55%, #b87333 80%, #0d0d0d 100%)"
  }
];
